;;; SPDX-FileCopyrightText: 2026 Wolfgang Corcoran-Mathe
;;; SPDX-License-Identifier: MIT

(library (steinmetz test runner)
  (export custom-test-runner-factory)
  (import (rnrs base)
          (rnrs io simple)
          (rnrs programs)
          (prefix (srfi :64) s64:)
          )

  (define (test-end runner)
    (case (s64:test-result-kind runner)
      ((pass)
       (display "Pass: ")
       (display (s64:test-runner-test-name runner))
       (newline))
      ((fail)
       (display "FAIL: ")
       (display (s64:test-runner-test-name runner))
       (display ". Expected ")
       (write (s64:test-result-ref runner 'expected-value))
       (display ", got ")
       (write (s64:test-result-ref runner 'actual-value))
       (display ".\n"))))

  (define (group-begin runner name count)
    (display "# Running test group ")
    (display name)
    (newline))

  (define (test-final runner)
    (display "===============================\n")
    (display "Total passes: ")
    (display (s64:test-runner-pass-count runner))
    (newline)
    (display "Total failures: ")
    (display (s64:test-runner-fail-count runner))
    (newline)
    (display "Total skips: ")
    (display (s64:test-runner-skip-count runner))
    (newline)
    (exit (if (zero? (s64:test-runner-fail-count runner)) 0 1)))

  (define (custom-test-runner-factory)
    (let ((runner (s64:test-runner-null)))
      (s64:test-runner-on-test-end! runner test-end)
      (s64:test-runner-on-group-begin! runner group-begin)
      (s64:test-runner-on-final! runner test-final)
      runner))

  )
